import pyautogui
import time
x = 0
lista = 100
pyautogui.alert("o código vai começar")
pyautogui.PAUSE = 0.3

for x in range(3):
    time.sleep(1)
    pyautogui.moveTo(786, 144)
    pyautogui.click()
    pyautogui.write('Secretaria Municipal da Habitacao')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('17.816.159/0001-81')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('cnpj')
    time.sleep(0.5)
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('5')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('0')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('0')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('0')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('0')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.press('tab')
    pyautogui.write('3')
    pyautogui.press('tab')
    pyautogui.moveTo(951, 661)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(472, 81)
    pyautogui.click()
    time.sleep(1)
    if pyautogui.press == 'p':
        print("You pressed p")
        break
